name = input("Enter your name:- ")
age = int(input("Enter your age:- "))
Branch = input("Enter your Branch:- ")
College = input("Enter your College:- ")
SGPA = float(input("Enter your SGPA:- "))
print("------STUDENT PROFILE------")
print(f"name    :- {name}")
print(f" age    :- {age}")
print(f"Branch  :- {Branch}")
print(f"College :- {College}")
print(f"SGPA    :- {SGPA}")
